# Generated by Django 3.1.4 on 2020-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                check=models.Q(balance__gte=0), name="balance_gte_0"
            ),
        ),
    ]
