version: '3.7'

services:
  db:
    image: postgres:11
    env_file: docker/development/docker.env

    ports:
      - 55432:5432

    volumes:
      - ../docker/volumes/db:/var/lib/postgresql/data

  cache:
    image: memcached

    ports:
      - 11211:1211

  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile

    env_file: docker/development/prod.env
    command: sh -c "/wait && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    ports:
      - "9000:8000"
      - "6900:6900"

    volumes:
      - .:/code/

    links:
      - db
      - cache

    environment:
      WAIT_HOSTS: db:5432
